[build-system]
requires = [
    "setuptools",
    "pillow",
    "torch",
    "torchvision",
    "pycocotools",
    "natsort",
    "tqdm",
    "torchmetrics",
]
build-backend = "setuptools.build_meta"
